<package>
  <name>AMBF</name>
  <version>2.0.0</version>
  <description>
  Asynchronous Multi-Body Framework (AMBF)
  </description>
  <maintainer email="anton.deguet@jhu.edu">Anton Deguet</maintainer>
  <license>xxx</license>
  <url>https://github.com/WPI-AIM/ambf</url>
  <depend>dvrk_arm</depend>
  <export>
    <build_type>catkin</build_type>
  </export>
</package>
