# Separation or penetration distance between object a (parent) and b
std_msgs/Float64 distance
# Contact point in world coordinates on object b
geometry_msgs/Vector3 contact_point
# Contact normal in world coordinates on object b
geometry_msgs/Vector3 contact_normal
# Contact point in local coordinates of object a
geometry_msgs/Vector3 local_point_a
# Contact point in local coordinates on object b
geometry_msgs/Vector3 local_point_b