Header header
string[] joint_names
string controller_name
trajectory_msgs/JointTrajectoryPoint desired
trajectory_msgs/JointTrajectoryPoint actual
---
trajectory_msgs/JointTrajectoryPoint control_output