name: ubuntu-20.04-ros-noetic

on:
  push:
    branches: [ ambf-3.0 ]
  pull_request:
    branches: [ ambf-3.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:noetic-desktop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      

      - name: Install Required Packages
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install -y software-properties-common
          sudo apt-get update
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y python3-catkin-tools libasound2-dev libgl1-mesa-dev xorg-dev libusb-1.0-0-dev
          
      - name: Initialize Catkin Workspace
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          mkdir -p ~/catkin_ws/src/
          cd ~/catkin_ws/src
          catkin_init_workspace
          cd ~/catkin_ws
          catkin build

      - name: Build Workspace
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          mkdir -p ~/catkin_ws/src/ambf
          cp -r . ~/catkin_ws/src/ambf
          cd ~/catkin_ws
          catkin build --summary --cmake-args -DCMAKE_BUILD_TYPE=Release