name: ubuntu-22.04-ros-humble

on:
  push:
    branches: [ ambf-3.0 ]
  pull_request:
    branches: [ ambf-3.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: osrf/ros:humble-desktop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Required Packages
        run: |
          sudo apt update
          sudo apt-get install -y software-properties-common
          sudo apt-get update
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libgl1-mesa-dev xorg-dev libusb-1.0-0-dev

      - name: Build workspace
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          mkdir -p ~/ros_ws/src/ambf
          cp -r . ~/ros_ws/src/ambf
          cd ~/ros_ws
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release